import { ApiError, type RemoteState } from '../../api/securepay/http';
import type { CommunityGateway } from '../../api/securepay/community';
import type {
  CircleMemberView, CircleMembershipResponse, CirclePendingInvitationView, CirclePendingRequestView, CircleResponse,
  CommunityHelpResponseView, CommunityObjectResponse, CommunityReplyResponse,
  FairTradePrincipleResponse, MembershipResponse,
} from '../../api/securepay/community/dto';
import type { DiscoveryGateway } from '../../api/securepay/discovery';
import type { DiscoveryResults, DiscoveryScope, PublicProfileResponse } from '../../api/securepay/discovery/dto';
import { searchResultsView, type StoreSearchResult } from '../../api/securepay/store/adapters';
import { searchRequests, mergeSearchResults } from '../store/view';
import type { StoreReadGateway } from '../store/view';
import type { CommunityObjectType } from '../../types';

export function errorText(error: unknown): string {
  if (error instanceof ApiError) {
    if (error.kind === 'network' || error.kind === 'timeout' || (error.status ?? 0) >= 500) return 'SecurePay is unavailable. Please try again.';
    return error.message;
  }
  return 'SecurePay could not complete this step. Please try again.';
}
function asApiError(error: unknown): ApiError {
  return error instanceof ApiError ? error : new ApiError('network', 'SecurePay is unavailable');
}
function newIdempotencyKey(prefix: string): string {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2)}`;
}
/**
 * Correction (Slice 2, second pre-merge pass) -- mirrors the backend's own KS Number normalization
 * (`TrustProjectMembershipService#normalizeKsNumber`: trim + uppercase) so the frontend's own "is
 * this the same target the key is already bound to" comparison agrees with what the backend
 * considers the same invitee, never a stricter or looser rule of its own.
 */
function normalizeKsNumberForComparison(value: string): string {
  return value.trim().toUpperCase();
}

export type CommunityView = 'home' | 'object' | 'compose' | 'circleDetail' | 'circleCompose' | 'search' | 'profile';
export type CommunityHomeTab = 'live' | 'circles' | 'discover';
export type CircleMembershipMode = 'OPEN' | 'REQUEST_TO_JOIN' | 'INVITE_ONLY';
export type CircleVisibility = 'PUBLIC' | 'PRIVATE';
const REAL_COMPOSE_TYPES: { value: CommunityObjectType; label: string }[] = [
  { value: 'question', label: 'Ask a question' },
  { value: 'need', label: 'Post a need' },
  { value: 'opportunity', label: 'Share an opportunity' },
  { value: 'work_story', label: 'Share a work story' },
  { value: 'discussion', label: 'Start a discussion' },
];
export { REAL_COMPOSE_TYPES };

export interface ComposeDraft {
  objectType: CommunityObjectType | null;
  title: string;
  body: string;
  locationLabel: string;
  submitting: boolean;
  error: string | null;
  /**
   * Phase 6 Slice 1 correction -- minted ONCE when the composer opens (`openComposer`), never
   * regenerated by `submitCompose` itself. It survives local validation failures, network failures,
   * ambiguous/backend rejections, and any number of repeated Submit presses against this same
   * unchanged draft, so a retry is a genuine retry, not a fresh duplicate creation attempt. It is
   * replaced only when a NEW composer session starts (`openComposer` mints a fresh one) -- which
   * happens after a confirmed success (the view leaves 'compose') or an explicit cancel/reset.
   */
  idempotencyKey: string;
}
const emptyDraft: ComposeDraft = { objectType: null, title: '', body: '', locationLabel: '', submitting: false, error: null, idempotencyKey: '' };

/**
 * Phase 6 (Community Life) Slice 2 -- The Trust Project membership, presented as a discriminated
 * state the UI can switch on directly, distinguishing "not signed in" from "signed in but not (yet)
 * a member" -- two genuinely different situations the raw backend `status: null`/401 conflate.
 */
export type MembershipUiState =
  | { kind: 'signed-out' }
  | { kind: 'loading' }
  | { kind: 'none' }
  | { kind: 'invited'; membership: MembershipResponse }
  | { kind: 'active'; membership: MembershipResponse }
  | { kind: 'declined'; membership: MembershipResponse }
  | { kind: 'revoked'; membership: MembershipResponse };

function toMembershipUiState(membership: MembershipResponse): MembershipUiState {
  switch (membership.status) {
    case null: return { kind: 'none' };
    case 'INVITED': return { kind: 'invited', membership };
    case 'ACTIVE': return { kind: 'active', membership };
    case 'DECLINED': return { kind: 'declined', membership };
    case 'REVOKED': return { kind: 'revoked', membership };
  }
}

export interface ReplyDraft { body: string; submitting: boolean; error: string | null; idempotencyKey: string }
const emptyReplyDraft: ReplyDraft = { body: '', submitting: false, error: null, idempotencyKey: '' };

export interface InviteDraft {
  ksNumber: string;
  submitting: boolean;
  error: string | null;
  sent: boolean;
  /**
   * Correction (Slice 2 pre-merge, first pass) -- minted ONCE when the invite panel opens
   * (`openInvite`), never regenerated by `submitInvite` itself. Discarded only on confirmed success
   * (a fresh key is minted immediately after, for whatever invitation follows) or an explicit
   * cancel/new invitation session (`openInvite` mints a fresh one).
   */
  idempotencyKey: string;
  /**
   * Correction (Slice 2 pre-merge, SECOND pass) -- the normalized invitee KS Number this draft's
   * `idempotencyKey` is permanently bound to, once a remote submission has actually been attempted;
   * `null` before any remote attempt, when the KS Number field may still be freely edited. Set on
   * the FIRST remote submission attempt and never changed afterward for this key -- this matches the
   * real backend's own contract that one invitation Idempotency-Key is permanently bound to one
   * invitee (`TrustProjectMembershipService#invite` rejects the same key replayed against a
   * different invitee). A retry after this is set must mean exactly "same invitee, same key";
   * changing the target is no longer a retry -- the caller must explicitly cancel and start a new
   * invitation (`openInvite` clears this and mints a fresh key).
   */
  attemptedTargetKsNumber: string | null;
}
const emptyInviteDraft: InviteDraft = {
  ksNumber: '', submitting: false, error: null, sent: false, idempotencyKey: '', attemptedTargetKsNumber: null,
};

/**
 * Phase 6 (Community Life) Slice 3 -- Circle creation draft. `idempotencyKey` follows the same
 * established lifecycle as `ComposeDraft`/`InviteDraft`: minted once when the create-Circle panel
 * opens (`openCreateCircle`), reused across every retry, replaced only after confirmed success or an
 * explicit cancel.
 */
export interface CreateCircleDraft {
  name: string;
  purpose: string;
  membershipMode: CircleMembershipMode;
  /** Correction (Slice 3 pre-merge completion pass) -- a SEPARATE choice from `membershipMode`: "who
   * can find this Circle?" (visibility) vs. "how do people join?" (membershipMode). */
  visibility: CircleVisibility;
  categoryLabel: string;
  locationLabel: string;
  submitting: boolean;
  error: string | null;
  idempotencyKey: string;
}
const emptyCreateCircleDraft: CreateCircleDraft = {
  name: '', purpose: '', membershipMode: 'OPEN', visibility: 'PUBLIC', categoryLabel: '', locationLabel: '',
  submitting: false, error: null, idempotencyKey: '',
};

export interface CommunityState {
  view: CommunityView;
  query: string;
  search: RemoteState<StoreSearchResult[]>;
  feed: RemoteState<CommunityObjectResponse[]>;
  selectedObjectId: string | null;
  selectedRealObject: CommunityObjectResponse | null;
  /** IDs of the signed-in caller's own objects (from `community.mine()`) -- empty and harmless when
   * signed out. Used only to decide whether to offer the author-only Close action; the backend
   * remains the real authority and independently enforces ownership regardless of this set. */
  ownObjectIds: ReadonlySet<string>;
  draft: ComposeDraft;
  notice: string | null;

  /** The Trust Project membership (Slice 2). Loaded on enter(); gates the real feed entirely. */
  membership: MembershipUiState;
  /**
   * Real replies/help for the currently-open object (Slice 2). Whether the caller currently HAS an
   * ACTIVE reply/help signal, and which one they may withdraw, is never tracked separately in this
   * state -- it is derived directly from each DTO's own server-derived `canWithdraw` field (see
   * `view.ts#myActiveHelpResponseId` and `CommunityResponse.canWithdraw`), so it survives a page
   * refresh/controller reload instead of relying on "did this session just create it" tracking.
   */
  objectReplies: RemoteState<CommunityReplyResponse[]>;
  objectHelp: RemoteState<CommunityHelpResponseView[]>;
  replyDraft: ReplyDraft;
  helpOffering: boolean;
  helpError: string | null;
  /**
   * Correction (Slice 2 pre-merge) -- the stable "I can help" intent key for the currently-open
   * object, minted once when the object opens (`openObject`) and reused across every retry of an "I
   * can help" attempt against this same intent, exactly the same idempotency-key-lifecycle fix as
   * `ReplyDraft.idempotencyKey`/`InviteDraft.idempotencyKey`. Never rely on "the database probably
   * converges it" as the primary mechanism -- frontend intent and backend idempotency must agree.
   * Replaced with a fresh key only after a confirmed withdrawal (a future "I can help" on this same
   * object is a genuinely new intent) or when a different object opens.
   */
  helpIntentKey: string;

  inviteOpen: boolean;
  inviteDraft: InviteDraft;

  principlesOpen: boolean;
  principles: RemoteState<FairTradePrincipleResponse[]>;

  // ─── Named Circles (Slice 3) -- "the homes inside The Trust Project" ─────────────────────────

  /** Which of the three distinct Community Home sections is showing -- Community LIVE (the wider
   * town square), Your Circles (the smaller spaces this person belongs to), or Discover Circles. */
  communityTab: CommunityHomeTab;
  discoverCircles: RemoteState<CircleResponse[]>;
  myCircles: RemoteState<CircleResponse[]>;
  createCircleOpen: boolean;
  createCircleDraft: CreateCircleDraft;

  selectedCircleId: string | null;
  selectedCircle: CircleResponse | null;
  /** The caller's own relationship to the currently-open Circle -- drives which action (Join/Request/
   * Accept/Decline/Leave) the detail view offers. Never inferred client-side. */
  circleMembership: RemoteState<CircleMembershipResponse>;
  /** The currently-open Circle's own scoped feed -- only ever loaded when the caller is an ACTIVE
   * member (or the owner); never fetched for a non-member, so private content is never requested. */
  circleObjects: RemoteState<CommunityObjectResponse[]>;
  /**
   * The stable join/request intent key for the currently-open Circle, minted once when it opens
   * (`openCircle`) and reused across every retry of a join/request attempt -- the same idempotency-
   * key-lifecycle discipline as `ReplyDraft`/`InviteDraft`/`helpIntentKey`.
   */
  circleJoinIntentKey: string;
  circleJoinSubmitting: boolean;
  circleJoinError: string | null;
  /** The Circle-scoped post composer -- the exact same draft shape as Community LIVE's own
   * `ComposeDraft`, including its idempotency-key lifecycle, just posting into a Circle instead. */
  circleComposeDraft: ComposeDraft;

  // ─── Correction (Slice 3 pre-merge completion pass): owner-side Circle management ─────────────────────────

  /** Owner-only. Loaded alongside membership when the Circle opens and the caller is its owner. */
  circlePendingRequests: RemoteState<CirclePendingRequestView[]>;
  /** ACTIVE members only. Loaded alongside the scoped feed for any ACTIVE member/owner. */
  circleMembers: RemoteState<CircleMemberView[]>;
  circleInviteOpen: boolean;
  /**
   * Final pre-merge correction pass -- the caller's own pending Circle invitations, self-scoped.
   * The one legitimate route to discover a PRIVATE Circle otherwise invisible to general discovery.
   * Loaded lazily alongside `myCircles` when the Circles tab is shown; opening one routes into the
   * existing Circle detail experience (`openCircle`) -- never a second accept/decline engine.
   */
  circleInvitations: RemoteState<CirclePendingInvitationView[]>;
  /** Reuses the SAME `InviteDraft` shape (and its own target-binding idempotency-key correction) as
   * Trust Project invitation -- one stable key permanently bound to one invitee once a remote
   * submission is attempted, exactly the same contract the backend enforces for Circle invitation. */
  circleInviteDraft: InviteDraft;
  circleCloseConfirmOpen: boolean;
  circleClosing: boolean;

  // ─── Phase 6 Slice 5 (Discovery & Identity) -- "find what actually exists, without SecurePay
  // deciding what is best for you" ─────────────────────────

  /** Discover Circles' own text query (Section 12) -- additive to the tab's existing unfiltered
   * browse; blank means the exact original behaviour. */
  discoverCirclesQuery: string;

  /** The one coherent Community discovery entry point (Section 28) -- `view: 'search'`. Never a
   * ranked/recommended result; `scope` narrows which section(s) are searched, matching the backend's
   * own EVERYTHING-preview-vs-one-scope-paginated contract. */
  searchQuery: string;
  searchScope: DiscoveryScope;
  discoverySearch: RemoteState<DiscoveryResults>;

  /** A public person/business profile, opened from a search result (`view: 'profile'`) -- never the
   * account/Settings experience (Section 34). */
  selectedProfileKsNumber: string | null;
  selectedProfile: RemoteState<PublicProfileResponse>;
}
const initial: CommunityState = {
  view: 'home', query: '', search: { status: 'idle' }, feed: { status: 'idle' },
  selectedObjectId: null, selectedRealObject: null, ownObjectIds: new Set(), draft: { ...emptyDraft }, notice: null,
  membership: { kind: 'loading' }, objectReplies: { status: 'idle' }, objectHelp: { status: 'idle' },
  replyDraft: { ...emptyReplyDraft }, helpOffering: false, helpError: null, helpIntentKey: '',
  inviteOpen: false, inviteDraft: { ...emptyInviteDraft },
  principlesOpen: false, principles: { status: 'idle' },
  communityTab: 'live', discoverCircles: { status: 'idle' }, myCircles: { status: 'idle' },
  createCircleOpen: false, createCircleDraft: { ...emptyCreateCircleDraft },
  selectedCircleId: null, selectedCircle: null, circleMembership: { status: 'idle' }, circleObjects: { status: 'idle' },
  circleJoinIntentKey: '', circleJoinSubmitting: false, circleJoinError: null,
  circleComposeDraft: { ...emptyDraft },
  circlePendingRequests: { status: 'idle' }, circleMembers: { status: 'idle' },
  circleInviteOpen: false, circleInvitations: { status: 'idle' }, circleInviteDraft: { ...emptyInviteDraft },
  circleCloseConfirmOpen: false, circleClosing: false,
  discoverCirclesQuery: '',
  searchQuery: '', searchScope: 'EVERYTHING', discoverySearch: { status: 'idle' },
  selectedProfileKsNumber: null, selectedProfile: { status: 'idle' },
};

type Gateway = Pick<StoreReadGateway, 'search'>;

/**
 * Phase 6 (Community Life) Slice 1/2 -- The Trust Project: real Question/Need/Opportunity/Work
 * Story/Discussion authority, real membership (invite/accept/decline), and real Conversation & Help
 * (reply/"I can help"), against the real backend (`createCommunityGateway`). Store-offer search
 * (Phase 10) is preserved unchanged and merged alongside the real feed -- Community continues to
 * reference Store rather than duplicate it. Nothing here ever creates Agreement/handoff/payment/
 * referral-reward authority -- see each backend service's own doctrine.
 */
export function createCommunityController(
  gateway: Gateway,
  community: CommunityGateway,
  discovery: DiscoveryGateway,
  trustedMediaOrigin: string | null = null,
) {
  let state: CommunityState = { ...initial };
  const listeners = new Set<() => void>();
  const update = (patch: Partial<CommunityState>) => { state = { ...state, ...patch }; listeners.forEach(listener => listener()); };

  let searchSequence = 0;
  async function runSearch(query: string) {
    const sequence = ++searchSequence;
    update({ query, search: { status: 'loading' } });
    try {
      const requests = searchRequests(query);
      const pages = await Promise.all(requests.map(params => gateway.search(params)));
      const results = mergeSearchResults(pages.map(page => searchResultsView(page, trustedMediaOrigin)));
      if (sequence !== searchSequence) return;
      update({ search: { status: 'ready', data: results } });
    } catch (error) {
      if (sequence !== searchSequence) return;
      update({ search: { status: 'error', error: asApiError(error) } });
    }
  }

  async function loadMembership() {
    update({ membership: { kind: 'loading' } });
    try {
      const membership = await community.membership.me();
      update({ membership: toMembershipUiState(membership) });
    } catch (error) {
      const apiError = asApiError(error);
      // A required-auth call the http client rejects locally (no token) surfaces as this exact
      // shape -- see createHttpClient's own 'Authentication required' -- distinguishing "not signed
      // in" from a genuine backend error the UI should otherwise report.
      if (apiError.status === 401 || apiError.code === 'AUTHENTICATION_REQUIRED') {
        update({ membership: { kind: 'signed-out' } });
      } else {
        update({ membership: { kind: 'none' }, notice: errorText(apiError) });
      }
    }
  }

  async function loadFeed() {
    update({ feed: { status: 'loading' } });
    try {
      const objects = await community.feed();
      update({ feed: { status: 'ready', data: objects } });
    } catch (error) {
      update({ feed: { status: 'error', error: asApiError(error) } });
    }
  }

  async function loadObjectConversation(objectId: string) {
    update({ objectReplies: { status: 'loading' }, objectHelp: { status: 'loading' } });
    try {
      const [replies, help] = await Promise.all([community.replies.list(objectId), community.help.list(objectId)]);
      update({ objectReplies: { status: 'ready', data: replies }, objectHelp: { status: 'ready', data: help } });
    } catch (error) {
      const err = asApiError(error);
      update({ objectReplies: { status: 'error', error: err }, objectHelp: { status: 'error', error: err } });
    }
  }

  function upsertFeedObject(object: CommunityObjectResponse) {
    if (state.feed.status !== 'ready') {
      update({ feed: { status: 'ready', data: [object] } });
      return;
    }
    const withoutExisting = state.feed.data.filter(o => o.id !== object.id);
    update({ feed: { status: 'ready', data: [object, ...withoutExisting] } });
  }

  /**
   * Phase 6 Slice 1 correction -- the backend feed is ACTIVE-only; a just-CLOSED object must leave
   * the current open feed immediately rather than being upserted back into it as a CLOSED row. Its
   * closed representation still lives on in `selectedRealObject` (current detail state) and would
   * appear in the author's own history (`mine()`) on a future load.
   */
  function removeFeedObject(id: string) {
    if (state.feed.status !== 'ready') return;
    update({ feed: { status: 'ready', data: state.feed.data.filter(o => o.id !== id) } });
  }

  // ─── Named Circles (Slice 3) ─────────────────────────

  async function loadMyCircles() {
    update({ myCircles: { status: 'loading' } });
    try {
      const circles = await community.circles.mine();
      update({ myCircles: { status: 'ready', data: circles } });
    } catch (error) {
      update({ myCircles: { status: 'error', error: asApiError(error) } });
    }
  }

  let discoverCirclesSequence = 0;
  async function loadDiscoverCircles(query?: string) {
    const sequence = ++discoverCirclesSequence;
    update({ discoverCircles: { status: 'loading' } });
    try {
      const circles = await community.circles.discover(50, 0, query || undefined);
      if (sequence !== discoverCirclesSequence) return;
      update({ discoverCircles: { status: 'ready', data: circles } });
    } catch (error) {
      if (sequence !== discoverCirclesSequence) return;
      update({ discoverCircles: { status: 'error', error: asApiError(error) } });
    }
  }

  // ─── Phase 6 Slice 5 (Discovery & Identity) ─────────────────────────

  let discoverySearchSequence = 0;
  async function runDiscoverySearch(query: string, scope: DiscoveryScope) {
    const sequence = ++discoverySearchSequence;
    update({ searchQuery: query, searchScope: scope, discoverySearch: { status: 'loading' } });
    try {
      const results = await discovery.search(query, scope);
      if (sequence !== discoverySearchSequence) return;
      update({ discoverySearch: { status: 'ready', data: results } });
    } catch (error) {
      if (sequence !== discoverySearchSequence) return;
      update({ discoverySearch: { status: 'error', error: asApiError(error) } });
    }
  }

  async function loadProfile(canonicalKsNumber: string) {
    update({ selectedProfileKsNumber: canonicalKsNumber, selectedProfile: { status: 'loading' } });
    try {
      const profile = await discovery.profiles.get(canonicalKsNumber);
      update({ selectedProfile: { status: 'ready', data: profile } });
    } catch (error) {
      update({ selectedProfile: { status: 'error', error: asApiError(error) } });
    }
  }

  /** Only ever called when the caller is a known ACTIVE member or the owner -- never for a
   * non-member, so private Circle content is never even requested. */
  async function loadCircleObjects(circleId: string) {
    update({ circleObjects: { status: 'loading' } });
    try {
      const objects = await community.circles.objects.list(circleId);
      update({ circleObjects: { status: 'ready', data: objects } });
    } catch (error) {
      update({ circleObjects: { status: 'error', error: asApiError(error) } });
    }
  }

  /** ACTIVE members only -- reused by both the caller's own view of who else is in the Circle and by
   * the owner (who is always an ACTIVE member of their own Circle). */
  async function loadCircleMembers(circleId: string) {
    update({ circleMembers: { status: 'loading' } });
    try {
      const members = await community.circles.members(circleId);
      update({ circleMembers: { status: 'ready', data: members } });
    } catch (error) {
      update({ circleMembers: { status: 'error', error: asApiError(error) } });
    }
  }

  /**
   * Final pre-merge correction pass -- the caller's own pending Circle invitations, self-scoped.
   * Never a generic search across every Circle's membership; the backend independently enforces this scoping.
   */
  async function loadCircleInvitations() {
    update({ circleInvitations: { status: 'loading' } });
    try {
      const invitations = await community.circles.myInvitations();
      update({ circleInvitations: { status: 'ready', data: invitations } });
    } catch (error) {
      update({ circleInvitations: { status: 'error', error: asApiError(error) } });
    }
  }

  /** Removes one Circle's invitation from the pending list after it is accepted or declined --
   * either way it must stop appearing as "waiting for me". */
  function removeCircleInvitation(circleId: string) {
    if (state.circleInvitations.status !== 'ready') return;
    update({ circleInvitations: { status: 'ready', data: state.circleInvitations.data.filter(i => i.circleId !== circleId) } });
  }

  /** Owner-only -- only ever called when the caller is already known to be the Circle's own owner. */
  async function loadCirclePendingRequests(circleId: string) {
    update({ circlePendingRequests: { status: 'loading' } });
    try {
      const pending = await community.circles.pendingRequests(circleId);
      update({ circlePendingRequests: { status: 'ready', data: pending } });
    } catch (error) {
      update({ circlePendingRequests: { status: 'error', error: asApiError(error) } });
    }
  }

  async function refreshCircleMembership(circleId: string) {
    try {
      const membership = await community.circles.membership(circleId);
      update({ circleMembership: { status: 'ready', data: membership } });
      if (membership.status === 'ACTIVE' || membership.isOwner) {
        await loadCircleObjects(circleId);
        await loadCircleMembers(circleId);
      }
      if (membership.isOwner && state.selectedCircle?.membershipMode === 'REQUEST_TO_JOIN') {
        await loadCirclePendingRequests(circleId);
      }
      return membership;
    } catch (error) {
      update({ circleMembership: { status: 'error', error: asApiError(error) } });
      return null;
    }
  }

  return {
    getSnapshot: (): CommunityState => state,
    subscribe: (listener: () => void) => { listeners.add(listener); return () => { listeners.delete(listener); }; },

    async enter() {
      if (state.search.status === 'idle') void runSearch('');
      await loadMembership();
      // Slice 2 convergence: the real feed/mine only ever succeed for an ACTIVE Trust Project
      // member -- attempting them for a non-member wastes a round trip that can only 403. The
      // store-offer search above is unaffected either way (Store retains its own separate authority).
      if (state.membership.kind === 'active') {
        if (state.feed.status === 'idle') await loadFeed();
        try {
          const mine = await community.mine();
          update({ ownObjectIds: new Set(mine.map(o => o.id)) });
        } catch { /* transiently unavailable -- Close affordance simply stays hidden */ }
      }
    },
    setQuery(query: string) { update({ query }); },
    async submitSearch() { await runSearch(state.query); },

    /** Opening a real Community object never creates Agreement/handoff authority -- pure local view switch. */
    async openObject(id: string) {
      const real = state.feed.status === 'ready' ? state.feed.data.find(o => o.id === id) ?? null : null;
      update({
        view: 'object', selectedObjectId: id, selectedRealObject: real,
        objectReplies: { status: 'idle' }, objectHelp: { status: 'idle' },
        replyDraft: { ...emptyReplyDraft, idempotencyKey: newIdempotencyKey('community-reply') },
        helpError: null, helpIntentKey: newIdempotencyKey('community-help'),
      });
      if (real) { await loadObjectConversation(id); return; }
      // Phase 6 Slice 5 (Discovery & Identity) -- opening a search result that is not already in the
      // locally-loaded LIVE feed (e.g. an older post, or one reached from Search rather than the
      // home feed) now falls back to a real fetch by id, mirroring `openCircle`'s own existing
      // fetch-fallback below -- never a silently-blank detail view.
      try {
        const fetched = await community.get(id);
        update({ selectedRealObject: fetched });
        await loadObjectConversation(id);
      } catch (error) {
        update({ notice: errorText(error) });
      }
    },
    backToHome() { update({ view: 'home', selectedObjectId: null, selectedRealObject: null }); },

    openComposer() { update({ view: 'compose', draft: { ...emptyDraft, idempotencyKey: newIdempotencyKey('community-create') } }); },
    cancelComposer() { update({ view: 'home', draft: { ...emptyDraft } }); },
    setComposeType(objectType: CommunityObjectType) { update({ draft: { ...state.draft, objectType, error: null } }); },
    setComposeField(field: 'title' | 'body' | 'locationLabel', value: string) {
      update({ draft: { ...state.draft, [field]: value, error: null } });
    },
    async submitCompose() {
      const { objectType, title, body, locationLabel, idempotencyKey } = state.draft;
      if (!objectType) { update({ draft: { ...state.draft, error: 'Choose what you would like to share.' } }); return; }
      if (!title.trim()) { update({ draft: { ...state.draft, error: 'Give it a short title.' } }); return; }
      if (!body.trim()) { update({ draft: { ...state.draft, error: 'Say a little more about it.' } }); return; }
      const backendType = objectType.toUpperCase();
      update({ draft: { ...state.draft, submitting: true, error: null } });
      try {
        // The SAME idempotencyKey minted when the composer opened is reused on every attempt against
        // this unchanged draft -- never regenerated here, so a retry after any failure (local
        // validation never reaches this point; network, ambiguous, or backend rejection all do) stays
        // a genuine retry rather than risking a duplicate post.
        const created = await community.create(
          backendType, title.trim(), body.trim(), locationLabel.trim() || null, idempotencyKey);
        upsertFeedObject(created);
        update({
          view: 'home', draft: { ...emptyDraft }, notice: 'Shared with the community.',
          ownObjectIds: new Set([...state.ownObjectIds, created.id]),
        });
      } catch (error) {
        update({ draft: { ...state.draft, submitting: false, error: errorText(error) } });
      }
    },

    /**
     * Closing is the author's own action only -- the backend independently enforces ownership,
     * using the exact same endpoint/authority for a Community LIVE object and a Circle-scoped one
     * (Circle ownership never grants authority over a member's own content). Removes the closed
     * object from whichever feed it was showing in, LIVE or the currently-open Circle's own scoped
     * feed -- each removal is a harmless no-op if the object was never in that particular list.
     */
    async closeObject(id: string) {
      try {
        const closed = await community.close(id);
        removeFeedObject(id);
        if (state.circleObjects.status === 'ready') {
          update({ circleObjects: { status: 'ready', data: state.circleObjects.data.filter(o => o.id !== id) } });
        }
        update({ selectedRealObject: closed, notice: 'Closed. It no longer appears in the open feed.' });
      } catch (error) {
        update({ notice: errorText(error) });
      }
    },

    // ─── The Trust Project membership (Slice 2) ─────────────────────────

    async acceptInvitation() {
      try {
        const membership = await community.membership.accept();
        update({ membership: toMembershipUiState(membership) });
        if (membership.status === 'ACTIVE') await this.enter();
      } catch (error) {
        update({ notice: errorText(error) });
      }
    },
    async declineInvitation() {
      try {
        const membership = await community.membership.decline();
        update({ membership: toMembershipUiState(membership) });
      } catch (error) {
        update({ notice: errorText(error) });
      }
    },
    openInvite() {
      update({ inviteOpen: true, inviteDraft: { ...emptyInviteDraft, idempotencyKey: newIdempotencyKey('community-invite') } });
    },
    cancelInvite() { update({ inviteOpen: false, inviteDraft: { ...emptyInviteDraft } }); },
    /**
     * Correction (Slice 2 pre-merge, second pass) -- once a remote submission has been attempted
     * (`inviteDraft.attemptedTargetKsNumber` is set), the target is permanently bound to this draft's
     * key and editing is refused here as a hard invariant, not merely disabled in the UI, so "one key,
     * one invitee" can never be silently violated even by a future UI bug. The caller must explicitly
     * cancel and start a new invitation (`openInvite`) to target someone else.
     */
    setInviteKsNumber(value: string) {
      if (state.inviteDraft.attemptedTargetKsNumber !== null) return;
      update({ inviteDraft: { ...state.inviteDraft, ksNumber: value, error: null } });
    },
    async submitInvite() {
      const boundTarget = state.inviteDraft.attemptedTargetKsNumber;
      if (!boundTarget) {
        // No remote attempt has happened yet -- local validation on the freely-editable field.
        if (!state.inviteDraft.ksNumber.trim()) {
          update({ inviteDraft: { ...state.inviteDraft, error: 'Enter their KS Number.' } });
          return;
        }
      }
      // The FIRST remote submission attempt binds this draft's key to the normalized target for
      // every subsequent retry -- see InviteDraft.attemptedTargetKsNumber's own doctrine comment.
      const target = boundTarget ?? normalizeKsNumberForComparison(state.inviteDraft.ksNumber);
      update({ inviteDraft: { ...state.inviteDraft, submitting: true, error: null, attemptedTargetKsNumber: target } });
      try {
        // The SAME (target, idempotencyKey) pair bound above is reused on every retry against this
        // unchanged draft -- never regenerated here, so a retry after any failure stays a genuine
        // retry of the same invitation intention, matching the backend's own "one key, one invitee"
        // contract rather than risking it being rejected as a conflicting reuse.
        await community.membership.invite(target, state.inviteDraft.idempotencyKey);
        // Confirmed success ends this invitation intention -- a fresh draft (and key) is minted
        // immediately so that inviting someone else without closing the panel starts its own new one.
        update({ inviteDraft: { ...emptyInviteDraft, sent: true, idempotencyKey: newIdempotencyKey('community-invite') }, notice: 'Invitation sent.' });
      } catch (error) {
        update({ inviteDraft: { ...state.inviteDraft, submitting: false, error: errorText(error) } });
      }
    },

    // ─── Conversation & Help (Slice 2) ─────────────────────────

    setReplyBody(value: string) { update({ replyDraft: { ...state.replyDraft, body: value, error: null } }); },
    async submitReply() {
      if (!state.selectedObjectId) return;
      const body = state.replyDraft.body.trim();
      if (!body) { update({ replyDraft: { ...state.replyDraft, error: 'Say something first.' } }); return; }
      update({ replyDraft: { ...state.replyDraft, submitting: true, error: null } });
      try {
        await community.replies.create(state.selectedObjectId, body, state.replyDraft.idempotencyKey);
        update({ replyDraft: { ...emptyReplyDraft, idempotencyKey: newIdempotencyKey('community-reply') } });
        await loadObjectConversation(state.selectedObjectId);
      } catch (error) {
        update({ replyDraft: { ...state.replyDraft, submitting: false, error: errorText(error) } });
      }
    },
    async withdrawReply(replyId: string) {
      if (!state.selectedObjectId) return;
      try {
        await community.replies.withdraw(state.selectedObjectId, replyId);
        await loadObjectConversation(state.selectedObjectId);
      } catch (error) {
        update({ notice: errorText(error) });
      }
    },

    /** "I can help" is a distinct willingness SIGNAL -- never a reply, never an Agreement, never a bid. */
    async offerHelp() {
      if (!state.selectedObjectId) return;
      update({ helpOffering: true, helpError: null });
      try {
        // The SAME helpIntentKey minted when this object opened is reused on every attempt against
        // this same intent -- never regenerated here, so a retry after any failure stays a genuine
        // retry rather than a fresh, distinct signal attempt.
        await community.help.offer(state.selectedObjectId, state.helpIntentKey);
        update({ helpOffering: false });
        await loadObjectConversation(state.selectedObjectId);
      } catch (error) {
        update({ helpOffering: false, helpError: errorText(error) });
      }
    },
    /**
     * Correction (Slice 2 pre-merge) -- `helpResponseId` is the caller's own real, currently ACTIVE
     * help response id, resolved by the caller (`CommunityExperience`) from the server-returned help
     * list's own `canWithdraw` field (`view.ts#myActiveHelpResponseId`) -- never from session state.
     */
    async withdrawHelp(helpResponseId: string) {
      if (!state.selectedObjectId) return;
      try {
        await community.help.withdraw(state.selectedObjectId, helpResponseId);
        // Confirmed withdrawal ends this intent -- a future "I can help" on this object is a
        // genuinely new intent and gets its own fresh key.
        update({ helpIntentKey: newIdempotencyKey('community-help') });
        await loadObjectConversation(state.selectedObjectId);
      } catch (error) {
        update({ notice: errorText(error) });
      }
    },

    // ─── Our 12 Principles (Slice 2) -- read from the one canonical source, never re-typed ─────────────────────────

    async togglePrinciples() {
      const opening = !state.principlesOpen;
      update({ principlesOpen: opening });
      if (opening && state.principles.status === 'idle') {
        update({ principles: { status: 'loading' } });
        try {
          const list = await community.principles();
          update({ principles: { status: 'ready', data: list } });
        } catch (error) {
          update({ principles: { status: 'error', error: asApiError(error) } });
        }
      }
    },

    // ─── Named Circles (Slice 3) -- "the homes inside The Trust Project" ─────────────────────────

    async showCommunityTab(tab: CommunityHomeTab) {
      update({ communityTab: tab });
      if (tab === 'circles') {
        if (state.myCircles.status === 'idle') await loadMyCircles();
        if (state.circleInvitations.status === 'idle') await loadCircleInvitations();
      }
      if (tab === 'discover' && state.discoverCircles.status === 'idle') await loadDiscoverCircles(state.discoverCirclesQuery);
    },

    /** Phase 6 Slice 5 (Discovery & Identity, Section 12) -- Discover Circles' own text query,
     * additive to its existing unfiltered browse; the caller debounces the resulting re-search
     * exactly like the existing home `query`/`submitSearch` pair. */
    setDiscoverCirclesQuery(query: string) { update({ discoverCirclesQuery: query }); },
    async submitDiscoverCirclesQuery() { await loadDiscoverCircles(state.discoverCirclesQuery); },

    openCreateCircle() {
      update({ createCircleOpen: true, createCircleDraft: { ...emptyCreateCircleDraft, idempotencyKey: newIdempotencyKey('circle-create') } });
    },
    cancelCreateCircle() { update({ createCircleOpen: false, createCircleDraft: { ...emptyCreateCircleDraft } }); },
    setCreateCircleField(field: 'name' | 'purpose' | 'categoryLabel' | 'locationLabel', value: string) {
      update({ createCircleDraft: { ...state.createCircleDraft, [field]: value, error: null } });
    },
    /**
     * Final pre-merge correction pass -- a PRIVATE Circle is server-enforced as INVITE_ONLY-only
     * (`CommunityCircleService#create`). This hard invariant here means the mode can never be
     * changed away from INVITE_ONLY while PRIVATE is selected, even if a future UI bug tried to --
     * mirroring, not merely hoping for, the backend's own rejection.
     */
    setCreateCircleMode(mode: CircleMembershipMode) {
      if (state.createCircleDraft.visibility === 'PRIVATE' && mode !== 'INVITE_ONLY') return;
      update({ createCircleDraft: { ...state.createCircleDraft, membershipMode: mode, error: null } });
    },
    /**
     * Choosing PRIVATE locks membershipMode to INVITE_ONLY immediately -- the only currently valid
     * combination -- so the impossible PRIVATE+OPEN/PRIVATE+REQUEST_TO_JOIN combination is never even
     * representable in the draft, let alone submitted only to fail server-side. Switching back to
     * PUBLIC leaves the mode as INVITE_ONLY (still valid for PUBLIC) rather than guessing a different
     * one the person did not choose.
     */
    setCreateCircleVisibility(visibility: CircleVisibility) {
      const membershipMode = visibility === 'PRIVATE' ? 'INVITE_ONLY' : state.createCircleDraft.membershipMode;
      update({ createCircleDraft: { ...state.createCircleDraft, visibility, membershipMode, error: null } });
    },
    async submitCreateCircle() {
      const { name, purpose, membershipMode, visibility, categoryLabel, locationLabel, idempotencyKey } = state.createCircleDraft;
      if (!name.trim()) { update({ createCircleDraft: { ...state.createCircleDraft, error: 'Give the Circle a name.' } }); return; }
      if (!purpose.trim()) { update({ createCircleDraft: { ...state.createCircleDraft, error: 'Say what this Circle is for.' } }); return; }
      update({ createCircleDraft: { ...state.createCircleDraft, submitting: true, error: null } });
      try {
        // The SAME idempotencyKey minted when the panel opened is reused on every attempt -- never
        // regenerated here, so a retry after any failure stays a genuine retry.
        const created = await community.circles.create(
          name.trim(), purpose.trim(), membershipMode, visibility, categoryLabel.trim() || null, locationLabel.trim() || null, idempotencyKey);
        const withoutExisting = state.myCircles.status === 'ready' ? state.myCircles.data.filter(c => c.id !== created.id) : [];
        update({
          createCircleOpen: false, createCircleDraft: { ...emptyCreateCircleDraft }, notice: 'Circle created.',
          myCircles: { status: 'ready', data: [created, ...withoutExisting] }, communityTab: 'circles',
        });
      } catch (error) {
        update({ createCircleDraft: { ...state.createCircleDraft, submitting: false, error: errorText(error) } });
      }
    },

    /** Opening a Circle never creates Agreement/handoff authority -- pure local view switch plus a
     * read of its discovery-safe fields and the caller's own membership state. */
    async openCircle(id: string) {
      const cached =
        (state.myCircles.status === 'ready' ? state.myCircles.data : [])
          .concat(state.discoverCircles.status === 'ready' ? state.discoverCircles.data : [])
          .find(c => c.id === id) ?? null;
      update({
        view: 'circleDetail', selectedCircleId: id, selectedCircle: cached,
        circleMembership: { status: 'loading' }, circleObjects: { status: 'idle' },
        circleJoinIntentKey: newIdempotencyKey('circle-join'), circleJoinError: null,
        circlePendingRequests: { status: 'idle' }, circleMembers: { status: 'idle' },
        circleInviteOpen: false, circleInviteDraft: { ...emptyInviteDraft },
        circleCloseConfirmOpen: false, circleClosing: false,
      });
      try {
        const circle = await community.circles.get(id);
        update({ selectedCircle: circle });
      } catch (error) {
        update({ notice: errorText(error) });
      }
      await refreshCircleMembership(id);
    },

    async joinCircle() {
      if (!state.selectedCircleId) return;
      update({ circleJoinSubmitting: true, circleJoinError: null });
      try {
        // The SAME circleJoinIntentKey minted when this Circle opened is reused on every retry.
        await community.circles.join(state.selectedCircleId, state.circleJoinIntentKey);
        await refreshCircleMembership(state.selectedCircleId);
        update({ circleJoinSubmitting: false });
      } catch (error) {
        update({ circleJoinSubmitting: false, circleJoinError: errorText(error) });
      }
    },
    async requestToJoinCircle() {
      if (!state.selectedCircleId) return;
      update({ circleJoinSubmitting: true, circleJoinError: null });
      try {
        await community.circles.request(state.selectedCircleId, state.circleJoinIntentKey);
        await refreshCircleMembership(state.selectedCircleId);
        update({ circleJoinSubmitting: false });
      } catch (error) {
        update({ circleJoinSubmitting: false, circleJoinError: errorText(error) });
      }
    },
    async acceptCircleInvitation() {
      if (!state.selectedCircleId) return;
      const circleId = state.selectedCircleId;
      try {
        await community.circles.acceptInvitation(circleId);
        // The invitation is now resolved -- it must stop appearing as "waiting for me", and the
        // Circle must appear in Your Circles the next time that list is read. Re-fetching (rather
        // than guessing the new server state locally) keeps both lists converged with the backend.
        removeCircleInvitation(circleId);
        if (state.myCircles.status !== 'idle') await loadMyCircles();
        await refreshCircleMembership(circleId);
      } catch (error) {
        update({ notice: errorText(error) });
      }
    },
    async declineCircleInvitation() {
      if (!state.selectedCircleId) return;
      const circleId = state.selectedCircleId;
      try {
        await community.circles.declineInvitation(circleId);
        // Resolved either way -- stops appearing as "waiting for me". The Circle itself becomes
        // unavailable again for a PRIVATE Circle (the backend's own visibility gate), never a stale
        // card left behind here.
        removeCircleInvitation(circleId);
        await refreshCircleMembership(circleId);
      } catch (error) {
        update({ notice: errorText(error) });
      }
    },
    /**
     * Self-only. Never leaves The Trust Project, never cancels Agreements, never deletes Store
     * access or public Community LIVE content -- see `CommunityCircleMembershipService#leave`'s own
     * doctrine comment for the exact backend guarantee this mirrors.
     *
     * <p>Correction (Slice 3 pre-merge completion pass): the owner cannot leave an ACTIVE Circle at
     * all this slice (no stewardship-transfer authority exists) -- the backend's own corrected error
     * message ("the Circle owner cannot leave while the Circle is active -- close the Circle
     * instead") is relayed verbatim via `errorText`, never papered over with an invented "transfer"
     * prompt the product does not actually support.
     */
    async leaveCircle() {
      if (!state.selectedCircleId) return;
      try {
        await community.circles.leave(state.selectedCircleId);
        update({ circleObjects: { status: 'idle' }, notice: 'You left this Circle.' });
        await refreshCircleMembership(state.selectedCircleId);
      } catch (error) {
        update({ notice: errorText(error) });
      }
    },

    // ─── Owner-only Circle management (Slice 3 pre-merge completion pass) ─────────────────────────

    async approveCircleRequest(membershipId: string) {
      if (!state.selectedCircleId) return;
      try {
        await community.circles.approveRequest(state.selectedCircleId, membershipId);
        await loadCirclePendingRequests(state.selectedCircleId);
        await refreshCircleMembership(state.selectedCircleId); // refreshes member count/list too
      } catch (error) {
        update({ notice: errorText(error) });
      }
    },
    async declineCircleRequest(membershipId: string) {
      if (!state.selectedCircleId) return;
      try {
        await community.circles.declineRequest(state.selectedCircleId, membershipId);
        await loadCirclePendingRequests(state.selectedCircleId);
      } catch (error) {
        update({ notice: errorText(error) });
      }
    },
    async removeCircleMember(membershipId: string) {
      if (!state.selectedCircleId) return;
      try {
        await community.circles.removeMember(state.selectedCircleId, membershipId);
        await loadCircleMembers(state.selectedCircleId);
        await refreshCircleMembership(state.selectedCircleId); // refreshes member count
      } catch (error) {
        update({ notice: errorText(error) });
      }
    },

    /**
     * Circle invitation is owner-only, and the invitee must already be an ACTIVE Trust Project
     * member -- see `CommunityCircleMembershipService#invite`'s own doctrine comment. Reuses the same
     * target-binding idempotency-key correction as Trust Project invitation: before any remote
     * attempt the KS Number may be freely edited; the first remote attempt binds this draft's key to
     * the normalized target for every retry.
     */
    openCircleInvite() {
      update({ circleInviteOpen: true, circleInviteDraft: { ...emptyInviteDraft, idempotencyKey: newIdempotencyKey('circle-invite') } });
    },
    cancelCircleInvite() { update({ circleInviteOpen: false, circleInviteDraft: { ...emptyInviteDraft } }); },
    setCircleInviteKsNumber(value: string) {
      if (state.circleInviteDraft.attemptedTargetKsNumber !== null) return;
      update({ circleInviteDraft: { ...state.circleInviteDraft, ksNumber: value, error: null } });
    },
    async submitCircleInvite() {
      if (!state.selectedCircleId) return;
      const boundTarget = state.circleInviteDraft.attemptedTargetKsNumber;
      if (!boundTarget && !state.circleInviteDraft.ksNumber.trim()) {
        update({ circleInviteDraft: { ...state.circleInviteDraft, error: 'Enter their KS Number.' } });
        return;
      }
      const target = boundTarget ?? normalizeKsNumberForComparison(state.circleInviteDraft.ksNumber);
      update({ circleInviteDraft: { ...state.circleInviteDraft, submitting: true, error: null, attemptedTargetKsNumber: target } });
      try {
        await community.circles.invite(state.selectedCircleId, target, state.circleInviteDraft.idempotencyKey);
        update({
          circleInviteDraft: { ...emptyInviteDraft, sent: true, idempotencyKey: newIdempotencyKey('circle-invite') },
          notice: 'Invitation sent.',
        });
      } catch (error) {
        update({ circleInviteDraft: { ...state.circleInviteDraft, submitting: false, error: errorText(error) } });
      }
    },

    openCircleCloseConfirm() { update({ circleCloseConfirmOpen: true }); },
    cancelCircleCloseConfirm() { update({ circleCloseConfirmOpen: false }); },
    /** Owner-only. Preserves history (posts, replies, help, membership); only stops new activity --
     * see `CommunityCircleService#close`'s own doctrine comment. Never deletes the Circle, never
     * deletes member accounts, never revokes Trust Project membership. */
    async confirmCloseCircle() {
      if (!state.selectedCircleId) return;
      update({ circleClosing: true });
      try {
        const closed = await community.circles.close(state.selectedCircleId);
        update({
          selectedCircle: closed, circleCloseConfirmOpen: false, circleClosing: false,
          notice: 'Circle closed. Existing posts and membership history are preserved.',
        });
      } catch (error) {
        update({ circleClosing: false, notice: errorText(error) });
      }
    },

    /** Leaving a Circle-scoped object's detail returns to that Circle's own detail view, never to
     * Community LIVE -- Circle content stays inside the Circle, including in navigation. */
    leaveCircleObjectDetail() {
      update({ view: 'circleDetail', selectedObjectId: null, selectedRealObject: null });
    },
    backToCommunityHome() {
      update({ view: 'home', selectedCircleId: null, selectedCircle: null, selectedObjectId: null, selectedRealObject: null });
    },

    /** Opening a real Circle-scoped Community object -- identical in every respect to opening a
     * Community LIVE object (`openObject`), sourced from the Circle's own feed instead of the LIVE
     * one. Replies/"I can help" reuse the exact same real authority either way. */
    async openCircleObject(id: string) {
      const real = state.circleObjects.status === 'ready' ? state.circleObjects.data.find(o => o.id === id) ?? null : null;
      update({
        view: 'object', selectedObjectId: id, selectedRealObject: real,
        objectReplies: { status: 'idle' }, objectHelp: { status: 'idle' },
        replyDraft: { ...emptyReplyDraft, idempotencyKey: newIdempotencyKey('community-reply') },
        helpError: null, helpIntentKey: newIdempotencyKey('community-help'),
      });
      if (real) await loadObjectConversation(id);
    },

    openCircleComposer() {
      update({ view: 'circleCompose', circleComposeDraft: { ...emptyDraft, idempotencyKey: newIdempotencyKey('circle-post') } });
    },
    cancelCircleComposer() { update({ view: 'circleDetail', circleComposeDraft: { ...emptyDraft } }); },
    setCircleComposeType(objectType: CommunityObjectType) {
      update({ circleComposeDraft: { ...state.circleComposeDraft, objectType, error: null } });
    },
    setCircleComposeField(field: 'title' | 'body' | 'locationLabel', value: string) {
      update({ circleComposeDraft: { ...state.circleComposeDraft, [field]: value, error: null } });
    },
    async submitCircleCompose() {
      if (!state.selectedCircleId) return;
      const { objectType, title, body, locationLabel, idempotencyKey } = state.circleComposeDraft;
      if (!objectType) { update({ circleComposeDraft: { ...state.circleComposeDraft, error: 'Choose what you would like to share.' } }); return; }
      if (!title.trim()) { update({ circleComposeDraft: { ...state.circleComposeDraft, error: 'Give it a short title.' } }); return; }
      if (!body.trim()) { update({ circleComposeDraft: { ...state.circleComposeDraft, error: 'Say a little more about it.' } }); return; }
      const backendType = objectType.toUpperCase();
      update({ circleComposeDraft: { ...state.circleComposeDraft, submitting: true, error: null } });
      try {
        const created = await community.circles.objects.create(
          state.selectedCircleId, backendType, title.trim(), body.trim(), locationLabel.trim() || null, idempotencyKey);
        const withoutExisting = state.circleObjects.status === 'ready' ? state.circleObjects.data.filter(o => o.id !== created.id) : [];
        update({
          view: 'circleDetail', circleComposeDraft: { ...emptyDraft }, notice: 'Shared with the Circle.',
          circleObjects: { status: 'ready', data: [created, ...withoutExisting] },
        });
      } catch (error) {
        update({ circleComposeDraft: { ...state.circleComposeDraft, submitting: false, error: errorText(error) } });
      }
    },

    showNotice(text: string) { update({ notice: text }); },
    dismissNotice() { update({ notice: null }); },

    // ─── Phase 6 Slice 5 (Discovery & Identity) -- "find → understand → open → decide for yourself" ─────

    /** Opens the one coherent Community discovery entry point (Section 28). Never auto-runs a search
     * on open -- the person types what they are looking for, exactly like every other real Community
     * search box in this app. */
    openSearch() { update({ view: 'search' }); },
    setSearchQuery(query: string) { update({ searchQuery: query }); },
    setSearchScope(scope: DiscoveryScope) { update({ searchScope: scope }); void runDiscoverySearch(state.searchQuery, scope); },
    async submitDiscoverySearch() { await runDiscoverySearch(state.searchQuery, state.searchScope); },

    /** Opens a public person/business profile from a search result (Section 34) -- informational
     * only; this is never itself a route to Agreement/trade authority (Section 37). */
    async openProfile(canonicalKsNumber: string) {
      update({ view: 'profile' });
      await loadProfile(canonicalKsNumber);
    },
    backToSearch() { update({ view: 'search' }); },

    reset() {
      update({
        ...initial, draft: { ...emptyDraft }, inviteDraft: { ...emptyInviteDraft }, replyDraft: { ...emptyReplyDraft },
        createCircleDraft: { ...emptyCreateCircleDraft }, circleComposeDraft: { ...emptyDraft },
        circleInviteDraft: { ...emptyInviteDraft },
      });
    },
  };
}
export type CommunityController = ReturnType<typeof createCommunityController>;
