import { ApiError, type RemoteState } from '../../api/securepay/http';
import type { CommunityGateway } from '../../api/securepay/community';
import type {
  CommunityHelpResponseView, CommunityObjectResponse, CommunityReplyResponse,
  FairTradePrincipleResponse, MembershipResponse,
} from '../../api/securepay/community/dto';
import { searchResultsView, type StoreSearchResult } from '../../api/securepay/store/adapters';
import { searchRequests, mergeSearchResults } from '../store/view';
import type { StoreReadGateway } from '../store/view';
import type { CommunityObjectType } from '../../types';

export function errorText(error: unknown): string {
  if (error instanceof ApiError) {
    if (error.kind === 'network' || error.kind === 'timeout' || (error.status ?? 0) >= 500) return 'SecurePay is unavailable. Please try again.';
    return error.message;
  }
  return 'SecurePay could not complete this step. Please try again.';
}
function asApiError(error: unknown): ApiError {
  return error instanceof ApiError ? error : new ApiError('network', 'SecurePay is unavailable');
}
function newIdempotencyKey(prefix: string): string {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2)}`;
}
/**
 * Correction (Slice 2, second pre-merge pass) -- mirrors the backend's own KS Number normalization
 * (`TrustProjectMembershipService#normalizeKsNumber`: trim + uppercase) so the frontend's own "is
 * this the same target the key is already bound to" comparison agrees with what the backend
 * considers the same invitee, never a stricter or looser rule of its own.
 */
function normalizeKsNumberForComparison(value: string): string {
  return value.trim().toUpperCase();
}

export type CommunityView = 'home' | 'object' | 'compose';
const REAL_COMPOSE_TYPES: { value: CommunityObjectType; label: string }[] = [
  { value: 'question', label: 'Ask a question' },
  { value: 'need', label: 'Post a need' },
  { value: 'opportunity', label: 'Share an opportunity' },
  { value: 'work_story', label: 'Share a work story' },
  { value: 'discussion', label: 'Start a discussion' },
];
export { REAL_COMPOSE_TYPES };

export interface ComposeDraft {
  objectType: CommunityObjectType | null;
  title: string;
  body: string;
  locationLabel: string;
  submitting: boolean;
  error: string | null;
  /**
   * Phase 6 Slice 1 correction -- minted ONCE when the composer opens (`openComposer`), never
   * regenerated by `submitCompose` itself. It survives local validation failures, network failures,
   * ambiguous/backend rejections, and any number of repeated Submit presses against this same
   * unchanged draft, so a retry is a genuine retry, not a fresh duplicate creation attempt. It is
   * replaced only when a NEW composer session starts (`openComposer` mints a fresh one) -- which
   * happens after a confirmed success (the view leaves 'compose') or an explicit cancel/reset.
   */
  idempotencyKey: string;
}
const emptyDraft: ComposeDraft = { objectType: null, title: '', body: '', locationLabel: '', submitting: false, error: null, idempotencyKey: '' };

/**
 * Phase 6 (Community Life) Slice 2 -- The Trust Project membership, presented as a discriminated
 * state the UI can switch on directly, distinguishing "not signed in" from "signed in but not (yet)
 * a member" -- two genuinely different situations the raw backend `status: null`/401 conflate.
 */
export type MembershipUiState =
  | { kind: 'signed-out' }
  | { kind: 'loading' }
  | { kind: 'none' }
  | { kind: 'invited'; membership: MembershipResponse }
  | { kind: 'active'; membership: MembershipResponse }
  | { kind: 'declined'; membership: MembershipResponse }
  | { kind: 'revoked'; membership: MembershipResponse };

function toMembershipUiState(membership: MembershipResponse): MembershipUiState {
  switch (membership.status) {
    case null: return { kind: 'none' };
    case 'INVITED': return { kind: 'invited', membership };
    case 'ACTIVE': return { kind: 'active', membership };
    case 'DECLINED': return { kind: 'declined', membership };
    case 'REVOKED': return { kind: 'revoked', membership };
  }
}

export interface ReplyDraft { body: string; submitting: boolean; error: string | null; idempotencyKey: string }
const emptyReplyDraft: ReplyDraft = { body: '', submitting: false, error: null, idempotencyKey: '' };

export interface InviteDraft {
  ksNumber: string;
  submitting: boolean;
  error: string | null;
  sent: boolean;
  /**
   * Correction (Slice 2 pre-merge, first pass) -- minted ONCE when the invite panel opens
   * (`openInvite`), never regenerated by `submitInvite` itself. Discarded only on confirmed success
   * (a fresh key is minted immediately after, for whatever invitation follows) or an explicit
   * cancel/new invitation session (`openInvite` mints a fresh one).
   */
  idempotencyKey: string;
  /**
   * Correction (Slice 2 pre-merge, SECOND pass) -- the normalized invitee KS Number this draft's
   * `idempotencyKey` is permanently bound to, once a remote submission has actually been attempted;
   * `null` before any remote attempt, when the KS Number field may still be freely edited. Set on
   * the FIRST remote submission attempt and never changed afterward for this key -- this matches the
   * real backend's own contract that one invitation Idempotency-Key is permanently bound to one
   * invitee (`TrustProjectMembershipService#invite` rejects the same key replayed against a
   * different invitee). A retry after this is set must mean exactly "same invitee, same key";
   * changing the target is no longer a retry -- the caller must explicitly cancel and start a new
   * invitation (`openInvite` clears this and mints a fresh key).
   */
  attemptedTargetKsNumber: string | null;
}
const emptyInviteDraft: InviteDraft = {
  ksNumber: '', submitting: false, error: null, sent: false, idempotencyKey: '', attemptedTargetKsNumber: null,
};

export interface CommunityState {
  view: CommunityView;
  query: string;
  search: RemoteState<StoreSearchResult[]>;
  feed: RemoteState<CommunityObjectResponse[]>;
  selectedObjectId: string | null;
  selectedRealObject: CommunityObjectResponse | null;
  /** IDs of the signed-in caller's own objects (from `community.mine()`) -- empty and harmless when
   * signed out. Used only to decide whether to offer the author-only Close action; the backend
   * remains the real authority and independently enforces ownership regardless of this set. */
  ownObjectIds: ReadonlySet<string>;
  draft: ComposeDraft;
  notice: string | null;

  /** The Trust Project membership (Slice 2). Loaded on enter(); gates the real feed entirely. */
  membership: MembershipUiState;
  /**
   * Real replies/help for the currently-open object (Slice 2). Whether the caller currently HAS an
   * ACTIVE reply/help signal, and which one they may withdraw, is never tracked separately in this
   * state -- it is derived directly from each DTO's own server-derived `canWithdraw` field (see
   * `view.ts#myActiveHelpResponseId` and `CommunityResponse.canWithdraw`), so it survives a page
   * refresh/controller reload instead of relying on "did this session just create it" tracking.
   */
  objectReplies: RemoteState<CommunityReplyResponse[]>;
  objectHelp: RemoteState<CommunityHelpResponseView[]>;
  replyDraft: ReplyDraft;
  helpOffering: boolean;
  helpError: string | null;
  /**
   * Correction (Slice 2 pre-merge) -- the stable "I can help" intent key for the currently-open
   * object, minted once when the object opens (`openObject`) and reused across every retry of an "I
   * can help" attempt against this same intent, exactly the same idempotency-key-lifecycle fix as
   * `ReplyDraft.idempotencyKey`/`InviteDraft.idempotencyKey`. Never rely on "the database probably
   * converges it" as the primary mechanism -- frontend intent and backend idempotency must agree.
   * Replaced with a fresh key only after a confirmed withdrawal (a future "I can help" on this same
   * object is a genuinely new intent) or when a different object opens.
   */
  helpIntentKey: string;

  inviteOpen: boolean;
  inviteDraft: InviteDraft;

  principlesOpen: boolean;
  principles: RemoteState<FairTradePrincipleResponse[]>;
}
const initial: CommunityState = {
  view: 'home', query: '', search: { status: 'idle' }, feed: { status: 'idle' },
  selectedObjectId: null, selectedRealObject: null, ownObjectIds: new Set(), draft: { ...emptyDraft }, notice: null,
  membership: { kind: 'loading' }, objectReplies: { status: 'idle' }, objectHelp: { status: 'idle' },
  replyDraft: { ...emptyReplyDraft }, helpOffering: false, helpError: null, helpIntentKey: '',
  inviteOpen: false, inviteDraft: { ...emptyInviteDraft },
  principlesOpen: false, principles: { status: 'idle' },
};

type Gateway = Pick<StoreReadGateway, 'search'>;

/**
 * Phase 6 (Community Life) Slice 1/2 -- The Trust Project: real Question/Need/Opportunity/Work
 * Story/Discussion authority, real membership (invite/accept/decline), and real Conversation & Help
 * (reply/"I can help"), against the real backend (`createCommunityGateway`). Store-offer search
 * (Phase 10) is preserved unchanged and merged alongside the real feed -- Community continues to
 * reference Store rather than duplicate it. Nothing here ever creates Agreement/handoff/payment/
 * referral-reward authority -- see each backend service's own doctrine.
 */
export function createCommunityController(
  gateway: Gateway,
  community: CommunityGateway,
  trustedMediaOrigin: string | null = null,
) {
  let state: CommunityState = { ...initial };
  const listeners = new Set<() => void>();
  const update = (patch: Partial<CommunityState>) => { state = { ...state, ...patch }; listeners.forEach(listener => listener()); };

  let searchSequence = 0;
  async function runSearch(query: string) {
    const sequence = ++searchSequence;
    update({ query, search: { status: 'loading' } });
    try {
      const requests = searchRequests(query);
      const pages = await Promise.all(requests.map(params => gateway.search(params)));
      const results = mergeSearchResults(pages.map(page => searchResultsView(page, trustedMediaOrigin)));
      if (sequence !== searchSequence) return;
      update({ search: { status: 'ready', data: results } });
    } catch (error) {
      if (sequence !== searchSequence) return;
      update({ search: { status: 'error', error: asApiError(error) } });
    }
  }

  async function loadMembership() {
    update({ membership: { kind: 'loading' } });
    try {
      const membership = await community.membership.me();
      update({ membership: toMembershipUiState(membership) });
    } catch (error) {
      const apiError = asApiError(error);
      // A required-auth call the http client rejects locally (no token) surfaces as this exact
      // shape -- see createHttpClient's own 'Authentication required' -- distinguishing "not signed
      // in" from a genuine backend error the UI should otherwise report.
      if (apiError.status === 401 || apiError.code === 'AUTHENTICATION_REQUIRED') {
        update({ membership: { kind: 'signed-out' } });
      } else {
        update({ membership: { kind: 'none' }, notice: errorText(apiError) });
      }
    }
  }

  async function loadFeed() {
    update({ feed: { status: 'loading' } });
    try {
      const objects = await community.feed();
      update({ feed: { status: 'ready', data: objects } });
    } catch (error) {
      update({ feed: { status: 'error', error: asApiError(error) } });
    }
  }

  async function loadObjectConversation(objectId: string) {
    update({ objectReplies: { status: 'loading' }, objectHelp: { status: 'loading' } });
    try {
      const [replies, help] = await Promise.all([community.replies.list(objectId), community.help.list(objectId)]);
      update({ objectReplies: { status: 'ready', data: replies }, objectHelp: { status: 'ready', data: help } });
    } catch (error) {
      const err = asApiError(error);
      update({ objectReplies: { status: 'error', error: err }, objectHelp: { status: 'error', error: err } });
    }
  }

  function upsertFeedObject(object: CommunityObjectResponse) {
    if (state.feed.status !== 'ready') {
      update({ feed: { status: 'ready', data: [object] } });
      return;
    }
    const withoutExisting = state.feed.data.filter(o => o.id !== object.id);
    update({ feed: { status: 'ready', data: [object, ...withoutExisting] } });
  }

  /**
   * Phase 6 Slice 1 correction -- the backend feed is ACTIVE-only; a just-CLOSED object must leave
   * the current open feed immediately rather than being upserted back into it as a CLOSED row. Its
   * closed representation still lives on in `selectedRealObject` (current detail state) and would
   * appear in the author's own history (`mine()`) on a future load.
   */
  function removeFeedObject(id: string) {
    if (state.feed.status !== 'ready') return;
    update({ feed: { status: 'ready', data: state.feed.data.filter(o => o.id !== id) } });
  }

  return {
    getSnapshot: (): CommunityState => state,
    subscribe: (listener: () => void) => { listeners.add(listener); return () => { listeners.delete(listener); }; },

    async enter() {
      if (state.search.status === 'idle') void runSearch('');
      await loadMembership();
      // Slice 2 convergence: the real feed/mine only ever succeed for an ACTIVE Trust Project
      // member -- attempting them for a non-member wastes a round trip that can only 403. The
      // store-offer search above is unaffected either way (Store retains its own separate authority).
      if (state.membership.kind === 'active') {
        if (state.feed.status === 'idle') await loadFeed();
        try {
          const mine = await community.mine();
          update({ ownObjectIds: new Set(mine.map(o => o.id)) });
        } catch { /* transiently unavailable -- Close affordance simply stays hidden */ }
      }
    },
    setQuery(query: string) { update({ query }); },
    async submitSearch() { await runSearch(state.query); },

    /** Opening a real Community object never creates Agreement/handoff authority -- pure local view switch. */
    async openObject(id: string) {
      const real = state.feed.status === 'ready' ? state.feed.data.find(o => o.id === id) ?? null : null;
      update({
        view: 'object', selectedObjectId: id, selectedRealObject: real,
        objectReplies: { status: 'idle' }, objectHelp: { status: 'idle' },
        replyDraft: { ...emptyReplyDraft, idempotencyKey: newIdempotencyKey('community-reply') },
        helpError: null, helpIntentKey: newIdempotencyKey('community-help'),
      });
      if (real) await loadObjectConversation(id);
    },
    backToHome() { update({ view: 'home', selectedObjectId: null, selectedRealObject: null }); },

    openComposer() { update({ view: 'compose', draft: { ...emptyDraft, idempotencyKey: newIdempotencyKey('community-create') } }); },
    cancelComposer() { update({ view: 'home', draft: { ...emptyDraft } }); },
    setComposeType(objectType: CommunityObjectType) { update({ draft: { ...state.draft, objectType, error: null } }); },
    setComposeField(field: 'title' | 'body' | 'locationLabel', value: string) {
      update({ draft: { ...state.draft, [field]: value, error: null } });
    },
    async submitCompose() {
      const { objectType, title, body, locationLabel, idempotencyKey } = state.draft;
      if (!objectType) { update({ draft: { ...state.draft, error: 'Choose what you would like to share.' } }); return; }
      if (!title.trim()) { update({ draft: { ...state.draft, error: 'Give it a short title.' } }); return; }
      if (!body.trim()) { update({ draft: { ...state.draft, error: 'Say a little more about it.' } }); return; }
      const backendType = objectType.toUpperCase();
      update({ draft: { ...state.draft, submitting: true, error: null } });
      try {
        // The SAME idempotencyKey minted when the composer opened is reused on every attempt against
        // this unchanged draft -- never regenerated here, so a retry after any failure (local
        // validation never reaches this point; network, ambiguous, or backend rejection all do) stays
        // a genuine retry rather than risking a duplicate post.
        const created = await community.create(
          backendType, title.trim(), body.trim(), locationLabel.trim() || null, idempotencyKey);
        upsertFeedObject(created);
        update({
          view: 'home', draft: { ...emptyDraft }, notice: 'Shared with the community.',
          ownObjectIds: new Set([...state.ownObjectIds, created.id]),
        });
      } catch (error) {
        update({ draft: { ...state.draft, submitting: false, error: errorText(error) } });
      }
    },

    /** Closing is the author's own action only -- the backend independently enforces ownership. */
    async closeObject(id: string) {
      try {
        const closed = await community.close(id);
        removeFeedObject(id);
        update({ selectedRealObject: closed, notice: 'Closed. It no longer appears in the open feed.' });
      } catch (error) {
        update({ notice: errorText(error) });
      }
    },

    // ─── The Trust Project membership (Slice 2) ─────────────────────────

    async acceptInvitation() {
      try {
        const membership = await community.membership.accept();
        update({ membership: toMembershipUiState(membership) });
        if (membership.status === 'ACTIVE') await this.enter();
      } catch (error) {
        update({ notice: errorText(error) });
      }
    },
    async declineInvitation() {
      try {
        const membership = await community.membership.decline();
        update({ membership: toMembershipUiState(membership) });
      } catch (error) {
        update({ notice: errorText(error) });
      }
    },
    openInvite() {
      update({ inviteOpen: true, inviteDraft: { ...emptyInviteDraft, idempotencyKey: newIdempotencyKey('community-invite') } });
    },
    cancelInvite() { update({ inviteOpen: false, inviteDraft: { ...emptyInviteDraft } }); },
    /**
     * Correction (Slice 2 pre-merge, second pass) -- once a remote submission has been attempted
     * (`inviteDraft.attemptedTargetKsNumber` is set), the target is permanently bound to this draft's
     * key and editing is refused here as a hard invariant, not merely disabled in the UI, so "one key,
     * one invitee" can never be silently violated even by a future UI bug. The caller must explicitly
     * cancel and start a new invitation (`openInvite`) to target someone else.
     */
    setInviteKsNumber(value: string) {
      if (state.inviteDraft.attemptedTargetKsNumber !== null) return;
      update({ inviteDraft: { ...state.inviteDraft, ksNumber: value, error: null } });
    },
    async submitInvite() {
      const boundTarget = state.inviteDraft.attemptedTargetKsNumber;
      if (!boundTarget) {
        // No remote attempt has happened yet -- local validation on the freely-editable field.
        if (!state.inviteDraft.ksNumber.trim()) {
          update({ inviteDraft: { ...state.inviteDraft, error: 'Enter their KS Number.' } });
          return;
        }
      }
      // The FIRST remote submission attempt binds this draft's key to the normalized target for
      // every subsequent retry -- see InviteDraft.attemptedTargetKsNumber's own doctrine comment.
      const target = boundTarget ?? normalizeKsNumberForComparison(state.inviteDraft.ksNumber);
      update({ inviteDraft: { ...state.inviteDraft, submitting: true, error: null, attemptedTargetKsNumber: target } });
      try {
        // The SAME (target, idempotencyKey) pair bound above is reused on every retry against this
        // unchanged draft -- never regenerated here, so a retry after any failure stays a genuine
        // retry of the same invitation intention, matching the backend's own "one key, one invitee"
        // contract rather than risking it being rejected as a conflicting reuse.
        await community.membership.invite(target, state.inviteDraft.idempotencyKey);
        // Confirmed success ends this invitation intention -- a fresh draft (and key) is minted
        // immediately so that inviting someone else without closing the panel starts its own new one.
        update({ inviteDraft: { ...emptyInviteDraft, sent: true, idempotencyKey: newIdempotencyKey('community-invite') }, notice: 'Invitation sent.' });
      } catch (error) {
        update({ inviteDraft: { ...state.inviteDraft, submitting: false, error: errorText(error) } });
      }
    },

    // ─── Conversation & Help (Slice 2) ─────────────────────────

    setReplyBody(value: string) { update({ replyDraft: { ...state.replyDraft, body: value, error: null } }); },
    async submitReply() {
      if (!state.selectedObjectId) return;
      const body = state.replyDraft.body.trim();
      if (!body) { update({ replyDraft: { ...state.replyDraft, error: 'Say something first.' } }); return; }
      update({ replyDraft: { ...state.replyDraft, submitting: true, error: null } });
      try {
        await community.replies.create(state.selectedObjectId, body, state.replyDraft.idempotencyKey);
        update({ replyDraft: { ...emptyReplyDraft, idempotencyKey: newIdempotencyKey('community-reply') } });
        await loadObjectConversation(state.selectedObjectId);
      } catch (error) {
        update({ replyDraft: { ...state.replyDraft, submitting: false, error: errorText(error) } });
      }
    },
    async withdrawReply(replyId: string) {
      if (!state.selectedObjectId) return;
      try {
        await community.replies.withdraw(state.selectedObjectId, replyId);
        await loadObjectConversation(state.selectedObjectId);
      } catch (error) {
        update({ notice: errorText(error) });
      }
    },

    /** "I can help" is a distinct willingness SIGNAL -- never a reply, never an Agreement, never a bid. */
    async offerHelp() {
      if (!state.selectedObjectId) return;
      update({ helpOffering: true, helpError: null });
      try {
        // The SAME helpIntentKey minted when this object opened is reused on every attempt against
        // this same intent -- never regenerated here, so a retry after any failure stays a genuine
        // retry rather than a fresh, distinct signal attempt.
        await community.help.offer(state.selectedObjectId, state.helpIntentKey);
        update({ helpOffering: false });
        await loadObjectConversation(state.selectedObjectId);
      } catch (error) {
        update({ helpOffering: false, helpError: errorText(error) });
      }
    },
    /**
     * Correction (Slice 2 pre-merge) -- `helpResponseId` is the caller's own real, currently ACTIVE
     * help response id, resolved by the caller (`CommunityExperience`) from the server-returned help
     * list's own `canWithdraw` field (`view.ts#myActiveHelpResponseId`) -- never from session state.
     */
    async withdrawHelp(helpResponseId: string) {
      if (!state.selectedObjectId) return;
      try {
        await community.help.withdraw(state.selectedObjectId, helpResponseId);
        // Confirmed withdrawal ends this intent -- a future "I can help" on this object is a
        // genuinely new intent and gets its own fresh key.
        update({ helpIntentKey: newIdempotencyKey('community-help') });
        await loadObjectConversation(state.selectedObjectId);
      } catch (error) {
        update({ notice: errorText(error) });
      }
    },

    // ─── Our 12 Principles (Slice 2) -- read from the one canonical source, never re-typed ─────────────────────────

    async togglePrinciples() {
      const opening = !state.principlesOpen;
      update({ principlesOpen: opening });
      if (opening && state.principles.status === 'idle') {
        update({ principles: { status: 'loading' } });
        try {
          const list = await community.principles();
          update({ principles: { status: 'ready', data: list } });
        } catch (error) {
          update({ principles: { status: 'error', error: asApiError(error) } });
        }
      }
    },

    showNotice(text: string) { update({ notice: text }); },
    dismissNotice() { update({ notice: null }); },

    reset() { update({ ...initial, draft: { ...emptyDraft }, inviteDraft: { ...emptyInviteDraft }, replyDraft: { ...emptyReplyDraft } }); },
  };
}
export type CommunityController = ReturnType<typeof createCommunityController>;
