import type {
  AgreementSummary,
  AgreementDetail,
  AttentionItem,
  WaitingItem,
  ActivityEntry,
} from './types';

export const demoAgreements: AgreementSummary[] = [
  {
    id: 'agr-bathroom',
    title: 'Bathroom retiling',
    counterparty: 'Peter Mwangi',
    counterpartyRole: 'Provider',
    amount: 'KES 68,000 labour',
    completion: '24 Oct 2026',
    status: 'change_requested',
    statusLabel: 'Change requested — Peter needs to confirm Demo v2',
    nextAction: 'Peter needs to confirm Demo v2',
    lastActivity: 'James set version 2',
    lastActivityTime: '14 Sep',
    version: 'v2',
    location: 'Westlands',
  },
  {
    id: 'agr-iphone',
    title: 'Used iPhone 15 Pro purchase',
    counterparty: 'Daniel Otieno',
    counterpartyRole: 'Seller',
    amount: 'KES 95,000',
    completion: '—',
    status: 'waiting_for_me',
    statusLabel: 'Waiting for your confirmation',
    nextAction: 'Review current version',
    lastActivity: 'Daniel set version 1',
    lastActivityTime: '15 Sep',
    version: 'v1',
    location: 'Kilimani',
  },
  {
    id: 'agr-chama',
    title: 'Greenfields Chama',
    counterparty: '7 members',
    counterpartyRole: 'Group',
    amount: 'KES 5,000 / month',
    completion: 'Ongoing',
    status: 'active',
    statusLabel: 'Active',
    nextAction: 'Next contribution due 18 Sep',
    lastActivity: 'Contribution recorded',
    lastActivityTime: 'Last week',
    version: 'v1',
  },
  {
    id: 'agr-kitchen',
    title: 'Kitchen renovation',
    counterparty: 'Peter Mwangi',
    counterpartyRole: 'Provider',
    amount: 'KES 320,000 labour',
    completion: '30 Nov 2026',
    status: 'completed',
    statusLabel: 'Completed',
    nextAction: '—',
    lastActivity: 'Peter confirmed completion',
    lastActivityTime: '30 Nov 2026',
    version: 'v3',
    location: 'Westlands',
  },
  {
    id: 'agr-plumbing',
    title: 'Plumbing repair',
    counterparty: 'Joseph Kamau',
    counterpartyRole: 'Provider',
    amount: 'KES 12,000',
    completion: '—',
    status: 'completed',
    statusLabel: 'Completed',
    nextAction: '—',
    lastActivity: 'Kamau completed kitchen leak repair',
    lastActivityTime: '6 months ago',
    version: 'v1',
    location: 'Karen',
  },
  {
    id: 'agr-shape',
    title: 'Solar installation',
    counterparty: 'Grace Wanjiru',
    counterpartyRole: 'Provider',
    amount: 'Not yet agreed',
    completion: 'Not yet set',
    status: 'taking_shape',
    statusLabel: 'Taking shape — still conversational',
    nextAction: 'Continue talking to Grace',
    lastActivity: 'You mentioned 8 panels',
    lastActivityTime: '2 hours ago',
    version: '—',
    location: 'Ruaka',
  },
  {
    id: 'agr-cancelled',
    title: 'Bathroom tiling with David',
    counterparty: 'David Otieno',
    counterpartyRole: 'Provider',
    amount: 'KES 55,000',
    completion: '—',
    status: 'cancelled',
    statusLabel: 'Cancelled',
    nextAction: '—',
    lastActivity: 'Cancelled by James — provider changed',
    lastActivityTime: '12 Sep 2026',
    version: 'v1',
  },
  {
    id: 'agr-expired',
    title: 'Bathroom tiling invitation',
    counterparty: 'David Otieno',
    counterpartyRole: 'Provider',
    amount: 'KES 55,000',
    completion: '—',
    status: 'expired',
    statusLabel: 'Expired',
    nextAction: '—',
    lastActivity: 'Invitation expired',
    lastActivityTime: '20 Sep 2026',
    version: 'v1',
  },
];

export const demoAttentionItems: AttentionItem[] = [
  {
    id: 'att-1',
    kind: 'agreement_changed',
    title: 'Bathroom retiling with Peter',
    detail: 'Peter requested a change to the completion date. No confirmation is expected yet — review the change.',
    actionLabel: 'Review change',
    actionValue: 'review_change_bathroom',
    agreementId: 'agr-bathroom',
  },
  {
    id: 'att-2',
    kind: 'waiting_confirmation',
    title: 'Used iPhone 15 Pro purchase',
    detail: 'Daniel set version 1. You are eligible to confirm — review and confirm the current version.',
    actionLabel: 'Confirm current version',
    actionValue: 'review_iphone',
    agreementId: 'agr-iphone',
  },
];

export const demoWaitingItems: WaitingItem[] = [
  {
    id: 'wait-1',
    title: 'Bathroom retiling',
    detail: 'Sent 14 Sep · Peter has joined · Not yet confirmed',
    statusText: 'Waiting for Peter',
    agreementId: 'agr-bathroom',
  },
  {
    id: 'wait-2',
    title: 'Greenfields Chama',
    detail: '2 organizers still need to confirm',
    statusText: 'Waiting for organizers',
    agreementId: 'agr-chama',
  },
  {
    id: 'wait-3',
    title: 'Solar installation',
    detail: 'Grace is reviewing the scope',
    statusText: 'Waiting for Grace',
    agreementId: 'agr-shape',
  },
];

export const demoRecentActivity: ActivityEntry[] = [
  { id: 'act-1', text: 'Grace added a quotation', time: '2 hours ago', agreementId: 'agr-shape' },
  { id: 'act-2', text: 'Agreement v2 created — Bathroom retiling', time: 'Yesterday', agreementId: 'agr-bathroom' },
  { id: 'act-3', text: 'Kamau completed kitchen leak repair', time: '6 months ago', agreementId: 'agr-plumbing' },
  { id: 'act-4', text: 'Greenfields Chama contribution recorded', time: 'Last week', agreementId: 'agr-chama' },
];

export const demoAgreementDetails: Record<string, AgreementDetail> = {
  'agr-bathroom': {
    id: 'agr-bathroom',
    title: 'Bathroom retiling with Peter Mwangi',
    status: 'change_requested',
    statusLabel: 'Change requested — Peter needs to confirm Demo v2',
    version: 'v2',
    people: [
      { name: 'James Kimani', role: 'Customer', confirmationStatus: 'confirmed_current' },
      { name: 'Peter Mwangi', role: 'Provider', confirmationStatus: 'joined_not_confirmed' },
    ],
    work: [
      'Remove old floor and wall tiles',
      'Dispose of old tiles',
      'Prepare surfaces',
      'Install replacement tiles',
    ],
    price: 'KES 68,000 labour',
    materials: 'Customer supplies: tiles, adhesive, grout',
    completion: '24 Oct 2026',
    conditions: [
      'Defect correction — not yet settled',
      'Payment timing — not yet settled',
    ],
    documents: [
      { id: 'doc-1', filename: 'Peter_Quote_Sept.pdf', type: 'Quotation', source: 'Added by Peter', date: '12 Sep 2026' },
      { id: 'doc-2', filename: 'Bathroom_photo_1.jpg', type: 'Photo', source: 'Added by James', date: '13 Sep 2026' },
      { id: 'doc-3', filename: 'Agreement_v2.pdf', type: 'Agreement record', source: 'SecurePay', date: '14 Sep 2026' },
    ],
    activity: [
      { date: '14 Sep', text: 'James set version 1' },
      { date: '14 Sep', text: 'Peter joined' },
      { date: '15 Sep', text: 'Peter requested completion date change' },
      { date: '15 Sep', text: 'Version 2 created' },
      { date: '15 Sep', text: 'James confirmed version 2' },
    ],
    changes: [
      {
        from: '20 Oct',
        to: '24 Oct',
        field: 'Completion date',
        requestedBy: 'Peter',
        reason: 'Needs two additional working days',
        status: 'accepted',
        date: '15 Sep',
      },
    ],
    versions: [
      { version: 'v2', confirmedBy: ['James'], isCurrent: true },
      { version: 'v1', confirmedBy: [], isCurrent: false },
    ],
    amount: 'KES 68,000 labour',
  },
  'agr-iphone': {
    id: 'agr-iphone',
    title: 'Used iPhone 15 Pro purchase',
    status: 'waiting_for_me',
    statusLabel: 'Waiting for your confirmation',
    version: 'v1',
    people: [
      { name: 'James Kimani', role: 'Buyer', confirmationStatus: 'joined_not_confirmed' },
      { name: 'Daniel Otieno', role: 'Seller', confirmationStatus: 'confirmed_current' },
    ],
    work: [
      'iPhone 15 Pro 256GB',
      'Original box and accessories',
      'Battery health 94%',
    ],
    price: 'KES 95,000',
    materials: '—',
    completion: '—',
    conditions: [
      'Inspection before payment',
      '7-day return window for undisclosed defects',
    ],
    documents: [
      { id: 'doc-4', filename: 'iPhone_photos.zip', type: 'Photos', source: 'Added by Daniel', date: '15 Sep 2026' },
    ],
    activity: [
      { date: '15 Sep', text: 'Daniel set version 1' },
      { date: '15 Sep', text: 'James joined' },
    ],
    changes: [],
    versions: [
      { version: 'v1', confirmedBy: ['Daniel'], isCurrent: true },
    ],
    amount: 'KES 95,000',
  },
  'agr-chama': {
    id: 'agr-chama',
    title: 'Greenfields Chama',
    status: 'active',
    statusLabel: 'Active',
    version: 'v1',
    people: [
      { name: 'James Kimani', role: 'Organizer', confirmationStatus: 'confirmed_current' },
      { name: '6 other members', role: 'Members', confirmationStatus: 'confirmed_current' },
      { name: '2 organizers', role: 'Organizers', confirmationStatus: 'not_joined' },
    ],
    work: [
      'Monthly contribution KES 5,000 per member',
      'Rotating payout schedule',
      '8 members total',
    ],
    price: 'KES 5,000 / month per member',
    materials: '—',
    completion: 'Ongoing',
    conditions: [
      'Governance: majority vote on major decisions',
      'Money authority: 2 of 3 organizers must approve payouts',
    ],
    documents: [
      { id: 'doc-5', filename: 'Chama_charter.pdf', type: 'Charter', source: 'Added by James', date: '1 Sep 2026' },
    ],
    activity: [
      { date: '1 Sep', text: 'Chama created with 8 members' },
      { date: '8 Sep', text: 'First contribution recorded' },
    ],
    changes: [],
    versions: [
      { version: 'v1', confirmedBy: ['James', '6 members'], isCurrent: true },
    ],
    amount: 'KES 5,000 / month',
  },
  'agr-kitchen': {
    id: 'agr-kitchen',
    title: 'Kitchen renovation with Peter Mwangi',
    status: 'completed',
    statusLabel: 'Completed',
    version: 'v3',
    people: [
      { name: 'James Kimani', role: 'Customer', confirmationStatus: 'confirmed_current' },
      { name: 'Peter Mwangi', role: 'Provider', confirmationStatus: 'confirmed_current' },
    ],
    work: [
      'Full kitchen renovation',
      'Cabinet installation',
      'Countertop fitting',
      'Plumbing and electrical for kitchen',
      'Tiling and finishing',
    ],
    price: 'KES 320,000 labour',
    materials: 'Customer supplied cabinets, countertops, tiles',
    completion: '30 Nov 2026',
    conditions: [
      'Defect correction: 30-day window after completion',
      'Payment: 50% start, 30% mid, 20% on completion',
    ],
    documents: [
      { id: 'doc-6', filename: 'Kitchen_before.jpg', type: 'Photo', source: 'Added by James', date: '15 Oct 2026' },
      { id: 'doc-7', filename: 'Kitchen_after.jpg', type: 'Photo', source: 'Added by James', date: '30 Nov 2026' },
      { id: 'doc-8', filename: 'Agreement_v3.pdf', type: 'Agreement record', source: 'SecurePay', date: '15 Oct 2026' },
    ],
    activity: [
      { date: '15 Oct', text: 'James set version 1' },
      { date: '15 Oct', text: 'Peter joined' },
      { date: '18 Oct', text: 'Version 2 created — scope expanded' },
      { date: '18 Oct', text: 'Both confirmed version 2' },
      { date: '25 Oct', text: 'Version 3 created — payment terms adjusted' },
      { date: '25 Oct', text: 'Both confirmed version 3' },
      { date: '30 Nov', text: 'Peter confirmed completion' },
    ],
    changes: [
      {
        from: 'Cabinets only',
        to: 'Full renovation including plumbing and electrical',
        field: 'Scope',
        requestedBy: 'James',
        reason: 'Decided to do the full kitchen at once',
        status: 'accepted',
        date: '18 Oct',
      },
      {
        from: '50% start, 50% completion',
        to: '50% start, 30% mid, 20% completion',
        field: 'Payment structure',
        requestedBy: 'Peter',
        reason: 'Mid-point work is substantial',
        status: 'accepted',
        date: '25 Oct',
      },
    ],
    versions: [
      { version: 'v3', confirmedBy: ['James', 'Peter'], isCurrent: true },
      { version: 'v2', confirmedBy: ['James', 'Peter'], isCurrent: false },
      { version: 'v1', confirmedBy: [], isCurrent: false },
    ],
    amount: 'KES 320,000 labour',
    completedDate: '30 Nov 2026',
  },
  'agr-plumbing': {
    id: 'agr-plumbing',
    title: 'Plumbing repair with Joseph Kamau',
    status: 'completed',
    statusLabel: 'Completed',
    version: 'v1',
    people: [
      { name: 'James Kimani', role: 'Customer', confirmationStatus: 'confirmed_current' },
      { name: 'Joseph Kamau', role: 'Provider', confirmationStatus: 'confirmed_current' },
    ],
    work: [
      'Kitchen leak repair',
      'Pipe replacement',
      'Wall re-sealing',
    ],
    price: 'KES 12,000',
    materials: 'Provider supplied pipes and sealant',
    completion: 'Same day',
    conditions: [
      '30-day defect window',
    ],
    documents: [
      { id: 'doc-9', filename: 'Repair_photo.jpg', type: 'Photo', source: 'Added by Kamau', date: '15 Mar 2026' },
    ],
    activity: [
      { date: '15 Mar', text: 'James set version 1' },
      { date: '15 Mar', text: 'Kamau joined and confirmed' },
      { date: '15 Mar', text: 'Kamau completed repair' },
    ],
    changes: [],
    versions: [
      { version: 'v1', confirmedBy: ['James', 'Kamau'], isCurrent: true },
    ],
    amount: 'KES 12,000',
    completedDate: '15 Mar 2026',
  },
  'agr-shape': {
    id: 'agr-shape',
    title: 'Solar installation with Grace Wanjiru',
    status: 'taking_shape',
    statusLabel: 'Taking shape — still conversational',
    version: '—',
    people: [
      { name: 'James Kimani', role: 'Customer', confirmationStatus: 'not_joined' },
      { name: 'Grace Wanjiru', role: 'Provider', confirmationStatus: 'not_joined' },
    ],
    work: [
      '8 solar panels (brand TBD)',
      'Inverter installation',
      'Battery storage',
    ],
    price: 'Not yet agreed',
    materials: '—',
    completion: 'Not yet set',
    conditions: [],
    documents: [
      { id: 'doc-10', filename: 'Grace_quote.pdf', type: 'Quotation', source: 'Added by Grace', date: '15 Sep 2026' },
    ],
    activity: [
      { date: '15 Sep', text: 'Conversation started' },
      { date: '15 Sep', text: 'Grace added a quotation' },
    ],
    changes: [],
    versions: [],
    amount: 'Not yet agreed',
  },
  'agr-cancelled': {
    id: 'agr-cancelled',
    title: 'Bathroom tiling with David Otieno',
    status: 'cancelled',
    statusLabel: 'Cancelled',
    version: 'v1',
    people: [
      { name: 'James Kimani', role: 'Customer', confirmationStatus: 'set_version' },
      { name: 'David Otieno', role: 'Provider', confirmationStatus: 'not_joined' },
    ],
    work: [
      'Bathroom floor tiling',
      'Grout and finish',
    ],
    price: 'KES 55,000',
    materials: 'Customer supplies tiles',
    completion: '—',
    conditions: [],
    documents: [],
    activity: [
      { date: '10 Sep', text: 'James set version 1' },
      { date: '12 Sep', text: 'Cancelled by James — provider changed' },
    ],
    changes: [],
    versions: [
      { version: 'v1', confirmedBy: [], isCurrent: false },
    ],
    amount: 'KES 55,000',
    cancelledReason: 'Provider changed — decided to go with Peter instead',
    cancelledBy: 'James',
    cancelledDate: '12 Sep 2026',
  },
  'agr-expired': {
    id: 'agr-expired',
    title: 'Bathroom tiling invitation',
    status: 'expired',
    statusLabel: 'Expired',
    version: 'v1',
    people: [
      { name: 'James Kimani', role: 'Customer', confirmationStatus: 'set_version' },
      { name: 'David Otieno', role: 'Provider', confirmationStatus: 'not_joined' },
    ],
    work: [
      'Bathroom floor tiling',
      'Grout and finish',
    ],
    price: 'KES 55,000',
    materials: 'Customer supplies tiles',
    completion: '—',
    conditions: [],
    documents: [],
    activity: [
      { date: '10 Sep', text: 'James set version 1' },
      { date: '10 Sep', text: 'Invitation sent to David' },
      { date: '20 Sep', text: 'Invitation expired — David did not join' },
    ],
    changes: [],
    versions: [
      { version: 'v1', confirmedBy: [], isCurrent: false },
    ],
    amount: 'KES 55,000',
    expiredReason: 'The invitation expired before David joined. No action required. History remains available.',
  },
};

export function getDemoAgreementDetail(id: string): AgreementDetail | undefined {
  return demoAgreementDetails[id];
}
